echo -e " $error    ██████ ▓██   ██▓ ███▄    █  ███▄    █ ▓█████   █████▒ ▒█████    $nocolour"
echo -e " $error ▒██    ▒  ▒██  ██▒ ██ ▀█   █  ██ ▀█   █ ▓█   ▀ ▓██   ▒ ▒██▒  ██▒   $nocolour"
echo -e " $error ░ ▓██▄     ▒██ ██░▓██  ▀█ ██▒▓██  ▀█ ██▒▒███   ▒████ ░ ▒██░  ██▒   $nocolour"
echo -e " $error   ▒   ██▒  ░ ▐██▓░▓██▒  ▐▌██▒▓██▒  ▐▌██▒▒▓█  ▄ ░▓█▒  ░ ▒██   ██░   $nocolour"
echo -e " $error ▒██████▒▒  ░ ██▒▓░▒██░   ▓██░▒██░   ▓██░░▒████▒░▒█░    ░ ████▓▒░   $nocolour"
echo -e " $error ▒ ▒▓▒ ▒ ░   ██▒▒▒ ░ ▒░   ▒ ▒ ░ ▒░   ▒ ▒ ░░ ▒░ ░ ▒ ░    ░ ▒░▒░▒░    $nocolour"
echo -e " $error ░ ░▒  ░ ░ ▓██ ░▒░ ░ ░░   ░ ▒░░ ░░   ░ ▒░ ░ ░  ░ ░        ░ ▒ ▒░    $nocolour"
echo -e " $error ░  ░  ░   ▒ ▒ ░░     ░   ░ ░    ░   ░ ░    ░    ░ ░    ░ ░ ░ ▒     $nocolour"
echo -e " $error       ░   ░ ░              ░          ░    ░  ░            ░ ░     $nocolour"
echo -e " $error           ░ ░                                                      $nocolour"
echo -e " $error                                                                    $nocolour"
                                                 